# Generated by Django 3.2 on 2021-06-23 10:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patients', '0002_alter_chatroom_user'),
        ('Admin1', '0002_medicalshop'),
    ]

    operations = [
        migrations.CreateModel(
            name='descriptions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=300)),
                ('datetime', models.DateTimeField(auto_now=True)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patients.booking')),
                ('medicalshop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admin1.medicalshop')),
            ],
        ),
    ]
