# Generated by Django 3.2 on 2021-06-24 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicalshop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='descriptions',
            name='code',
            field=models.TextField(blank=True, null=True),
        ),
    ]
