# Generated by Django 3.2 on 2021-06-26 11:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0003_booking_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='image',
        ),
    ]
