# Generated by Django 3.2 on 2021-05-26 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0003_booking'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='time_end',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='time_start',
        ),
        migrations.AddField(
            model_name='booking',
            name='slot',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
