# Generated by Django 3.2 on 2021-06-26 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0004_remove_booking_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='patients',
            name='image',
            field=models.ImageField(default=1, upload_to='media/'),
            preserve_default=False,
        ),
    ]
